apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: alert-svc
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/fis2425/alert:latest
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: NODE_ENV
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: KAFKA_HOST
            - name: API_PREFIX
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: API_PREFIX
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: SENDGRID_API_KEY
            - name: FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: alert-secrets
                  key: FROM_EMAIL
          securityContext:
            runAsUser: 0
