apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api-gateway
    tier: backend
  name: api-gateway
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: api-gateway
    app: api-gateway
