apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: rabbitmq-appointment
  name: rabbitmq-appointment
spec:
  type: ClusterIP
  ports:
    - protocol: TCP 
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: rabbitmq-appointment
