apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: rabbitmq-appointment
  name: rabbitmq-appointment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq-appointment
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: rabbitmq-appointment
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: RABBIT_PASSWORD
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: RABBIT_USERNAME
          image: rabbitmq:management-alpine
          name: rabbitmq-appointment
          ports:
            - containerPort: 5672
              protocol: TCP
      restartPolicy: Always
