apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: appointment
  name: appointment
spec:
  type: ClusterIP
  ports:
    - protocol: TCP 
      port: 3012
      targetPort: 3012
  selector:
    io.kompose.service: appointment
