apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: appointment
  name: appointment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appointment
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: appointment
    spec:
      containers:
        - env:
            - name: API_PREFIX
              value: /api/v1
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: JWT_SECRET
            - name: MONGOADMIN
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: MONGOADMIN
            - name: MONGOPASS
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: MONGOPASS
            - name: MONGOURL
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: MONGOURL
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3012"
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: RABBIT_HOST
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: RABBIT_PASSWORD
            - name: RABBIT_PORT
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: RABBIT_PORT
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: RABBIT_USERNAME
            - name: RABBIT_VHOST
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: RABBIT_VHOST
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: KAFKA_HOST
            - name: DRAGONFLY_HOST
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: DRAGONFLY_HOST
            - name: DRAGONFLY_PORT
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: DRAGONFLY_PORT
          image: ghcr.io/fis2425/appointment:latest
          name: appointment
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 3012
            initialDelaySeconds: 20
            periodSeconds: 5
          ports:
            - containerPort: 3012
              protocol: TCP
      restartPolicy: Always
