apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: dragonfly-appointment
  name: dragonfly-appointment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dragonfly-appointment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: dragonfly-appointment
    spec:
      containers:
        - image: ghcr.io/dragonflydb/dragonfly:latest
          name: dragonfly-appointment
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data/dragonfly
              name: dragonfly-data
      restartPolicy: Always
      volumes:
        - name: dragonfly-data
          persistentVolumeClaim:
            claimName: dragonfly-data
