apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: dragonfly-auth
  name: dragonfly-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dragonfly-auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: dragonfly-auth
    spec:
      containers:
        - image: ghcr.io/dragonflydb/dragonfly:latest
          name: dragonfly-auth
          livenessProbe:
            exec:
              command:
              - redis-cli
              - --raw
              - incr
              - ping
            initialDelaySeconds: 15
            periodSeconds: 5
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data/dragonfly
              name: dragonfly-auth
      restartPolicy: Always
      volumes:
        - name: dragonfly-auth
          persistentVolumeClaim:
            claimName: dragonfly-auth
