apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-auth
  name: mongo-auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
