apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: authorization-svc
  name: authorization-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: authorization-svc
