apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: authorization-svc
  name: authorization-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authorization-svc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: authorization-svc
    spec:
      containers:
        - env:
            - name: API_PREFIX
              value: /api/v1
            - name: DRAGONFLY_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DRAGONFLY_HOST
            - name: DRAGONFLY_PORT
              value: "6379"
            - name: JWT_EXPIRATION
              value: "3600"
            - name: JWT_REFRESH_EXPIRATION
              value: "604800"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: KAFKA_HOST
            - name: MONGOADMIN
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: MONGOADMIN
            - name: MONGOPASS
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: MONGOPASS
            - name: SECURE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: SECURE_COOKIE
            - name: DEV_COOKIE
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DEV_COOKIE
            - name: MONGOURL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: MONGOURL
            - name: NODE_ENV
              value: production
          image: ghcr.io/fis2425/authorization:latest
          imagePullPolicy: Always
          name: authorization-svc
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 5
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
